In [1]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
from torch import nn
from tqdm.auto import tqdm
from torchvision import transforms
from torchvision.utils import make_grid
from torch.utils.data import DataLoader

In [5]:
n_test_samples = 100
real = torch.ones(n_test_samples, 1)
fake = torch.zeros(n_test_samples,1)

In [6]:
real.shape

torch.Size([100, 1])

In [7]:
fake.shape

torch.Size([100, 1])

In [8]:
# x=torch.tensor([False, False, True, False,False])
# y=torch.tensor([10,20,30,40,50])
# z=torch.tensor([15,25,35,45,55])
# i=y.clone() # i = [10,20,30,40,50]
# print(i)
# # masking i using x to get values from z
# i[x]=z[x] # i= [10, 20, 35, 40, 50]
# print(i)
# I hope this is helpful

In [12]:
index_matrix=torch.rand(len(real))
index_matrix.shape
p_real = 0.2

In [26]:
index_matrix

tensor([0.6316, 0.2445, 0.0862, 0.7663, 0.5388, 0.6584, 0.7923, 0.6626, 0.8022,
        0.3877, 0.6442, 0.6173, 0.9479, 0.0760, 0.3003, 1.0000, 0.3426, 0.3655,
        0.6732, 0.7333, 0.2985, 0.3051, 0.8008, 0.2523, 0.2030, 0.7436, 0.3923,
        0.2825, 0.6484, 0.2572, 0.9546, 0.4043, 0.3704, 0.5402, 0.2419, 0.3153,
        0.5593, 0.0287, 0.1917, 0.9359, 0.2729, 0.4581, 0.0607, 0.3374, 0.5578,
        0.2632, 0.4823, 0.9899, 0.8333, 0.4194, 0.4105, 0.5419, 0.8151, 0.1200,
        0.1463, 0.7634, 0.3842, 0.4933, 0.1310, 0.7157, 0.7656, 0.1599, 0.1263,
        0.1219, 0.3632, 0.5466, 0.0093, 0.1286, 0.1976, 0.7025, 0.7575, 0.0971,
        0.2902, 0.9816, 0.0730, 0.3663, 0.9258, 0.3773, 0.3556, 0.3053, 0.4094,
        0.6468, 0.4117, 0.9455, 0.6738, 0.9799, 0.6769, 0.5867, 0.0649, 0.2755,
        0.6035, 0.7859, 0.0222, 0.4793, 0.1885, 0.0227, 0.5377, 0.6218, 0.5273,
        0.5302])

In [15]:
index_matrix_ber=torch.bernoulli(index_matrix, p_real).bool()
index_matrix_ber

tensor([False,  True, False, False, False, False,  True, False, False, False,
         True, False, False, False, False, False, False, False, False,  True,
         True, False, False, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True, False,  True,
        False, False, False, False, False, False, False,  True,  True, False,
        False,  True,  True,  True, False, False,  True,  True,  True,  True,
        False, False,  True,  True, False, False, False,  True, False, False,
         True, False, False, False, False, False, False, False, False, False,
         True, False, False,  True, False,  True, False,  True,  True, False])

In [17]:
real[0][0]

tensor(1.)

In [21]:
real.shape[0]

100

In [25]:
index_matrix[1]

tensor(0.2445)

In [29]:
index_matrix_test=torch.rand(len(real),2)
index_matrix_test

tensor([[4.7254e-01, 4.9982e-01],
        [3.6453e-01, 4.7567e-01],
        [1.1325e-01, 9.4423e-01],
        [6.9872e-01, 8.3560e-01],
        [5.2601e-01, 6.8122e-02],
        [9.7820e-01, 6.5800e-01],
        [2.0954e-02, 9.9735e-01],
        [6.1772e-01, 1.2374e-01],
        [5.8884e-01, 9.8922e-01],
        [5.9302e-01, 5.2026e-01],
        [7.3991e-01, 2.0577e-01],
        [7.4778e-01, 3.6484e-01],
        [6.7071e-01, 3.0848e-01],
        [1.3315e-01, 8.9807e-01],
        [8.3513e-01, 2.5715e-01],
        [6.4583e-02, 4.7008e-01],
        [4.8130e-01, 9.5794e-01],
        [5.0259e-01, 4.5716e-01],
        [1.7115e-01, 3.8630e-01],
        [2.8897e-01, 5.2308e-01],
        [3.7527e-01, 3.3431e-01],
        [9.7956e-01, 7.8294e-02],
        [5.4166e-02, 3.5198e-01],
        [9.0869e-01, 6.9255e-01],
        [5.8329e-01, 9.2620e-01],
        [8.1390e-01, 4.3529e-04],
        [7.3470e-01, 4.1919e-01],
        [5.4526e-01, 9.3430e-01],
        [7.7148e-02, 9.5493e-01],
        [5.791

In [30]:
index_matrix_test.shape

torch.Size([100, 2])

In [31]:
index_matrix_test[0][0]

tensor(0.4725)